trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureMysqlDeployment@1
  inputs:
    azureSubscription: 'Azure for Students (d83b14d9-910d-4b55-82eb-b8248af5cd30)'
    ServerName: 'stproj-2022-sqlserver.database.windows.net'
    DatabaseName: 'BankAppDB'
    SqlUsername: 'BankAppAdmin'
    SqlPassword: 'BankApp!'
    TaskNameSelector: 'InlineSqlTask'
    SqlInline: |
      DROP TABLE [dbo].[AspNetUserTokens]
      DROP TABLE [dbo].[AspNetUserRoles]
      DROP TABLE [dbo].[AspNetUserClaims]
      DROP TABLE [dbo].[AspNetUserLogins]
      DROP TABLE [dbo].[AspNetRoleClaims]
      DROP TABLE [dbo].[Transactions]
      DROP TABLE [dbo].[AspNetRoles]
      DROP TABLE [dbo].[AspNetUsers]
      DROP TABLE [dbo].[__EFMigrationsHistory]
    IpDetectionMethod: 'AutoDetect'