trigger:
- master

pool:
  vmImage: windows-latest

variables:
- group: SQL Connection Variables

steps:
- task: SqlDacpacDeploymentOnMachineGroup@0
  displayName: Run SQL Query
  inputs:
    TaskType: 'sqlInline'
    InlineSql: |
      DROP TABLE IF EXISTS [dbo].[AspNetUserTokens]
      DROP TABLE IF EXISTS [dbo].[AspNetUserRoles]
      DROP TABLE IF EXISTS [dbo].[AspNetUserClaims]
      DROP TABLE IF EXISTS [dbo].[AspNetUserLogins]
      DROP TABLE IF EXISTS [dbo].[AspNetRoleClaims]
      DROP TABLE IF EXISTS [dbo].[Transactions]
      DROP TABLE IF EXISTS [dbo].[AspNetRoles]
      DROP TABLE IF EXISTS [dbo].[AspNetUsers]
      DROP TABLE IF EXISTS [dbo].[__EFMigrationsHistory]
    ServerName: '$(SQL_HOST),1433'
    DatabaseName: '$(SQL_DB)'
    AuthScheme: 'sqlServerAuthentication'
    SqlUsername: '$(SQL_USER)'
    SqlPassword: '$(SQL_PASSWORD)'
 