trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: MysqlDeploymentOnMachineGroup@1
  inputs:
    TaskNameSelector: 'InlineSqlTask'
    SqlInline: |
      DROP TABLE [dbo].[AspNetUserTokens]
      DROP TABLE [dbo].[AspNetUserRoles]
      DROP TABLE [dbo].[AspNetUserClaims]
      DROP TABLE [dbo].[AspNetUserLogins]
      DROP TABLE [dbo].[AspNetRoleClaims]
      DROP TABLE [dbo].[Transactions]
      DROP TABLE [dbo].[AspNetRoles]
      DROP TABLE [dbo].[AspNetUsers]
      DROP TABLE [dbo].[__EFMigrationsHistory]
    ServerName: 'stproj-2022-sqlserver.database.windows.net'
    DatabaseName: 'BankAppDB'
    SqlUsername: 'BankAppAdmin'
    SqlPassword: '$(SQL_PASSWORD)'

 