using System.ComponentModel.DataAnnotations;
using System.Web;
using System.ComponentModel;

namespace BankApp.Models
{
    public class ApplicationUser
    {
        public ApplicationUser()
        {
            this.Transactions = new List<TransactionModel>();
        }
        //Account Identification/Autogenerated Information
        [Key]
        public int UserID { get; set; }

        [Required]
        [StringLength(7, MinimumLength = 7)]
        public string PIN { get; set; }

        [DefaultValue("Active")]
        public string? Status { get; set; }

        public List<TransactionModel>? Transactions { get; set; }

        [DefaultValue(0.00)]
        public decimal Balance { get; set; }

        //Account Signup Information
        //Validation annotations are not required here as this model is only for backend purposes.
        [Required]
        public string FirstName { get; set; }


        [Required]
        public string LastName { get; set; }


        [Required]
        public string Address1 { get; set; }


        public string? Address2 { get; set; }


        [Required]
        public string City { get; set; }


        [Required]
        public string County { get; set; }


        [Required]
        public string Eircode { get; set; }


        [Required]
        public string PhoneNumber { get; set; }


        [Required]
        public string Email { get; set; }
    }
}
