using System.ComponentModel.DataAnnotations;
using System.Web;
using System.ComponentModel;

namespace BankApp.Models
{
    public class AccountModel
    {
        //Account Identification/Autogenerated Information
        [Key]
        [Required]
        public int UserID { get; set; }

        [MinLength(6)]
        [MaxLength(6)]
        [Required]
        public int PIN { get; set; }

        [DefaultValue("Active")]
        public string Status { get; set; }

        public List<TransactionModel> Transactions { get; set; }

        [Required]
        [DefaultValue(0.00)]
        public decimal Balance { get; set; }

        //Account Signup Information
        [Required(ErrorMessage = "A First Name is required.")]
        [RegularExpression("^[a-zA-Z ]*$")]
        public string FirstName { get; set; }


        [Required(ErrorMessage = "A Last Name is required.")]
        [RegularExpression("^[a-zA-Z ]*$")]
        public string LastName { get; set; }


        [Required(ErrorMessage = "Address is required.")]
        public string Address1 { get; set; }


        public string Address2 { get; set; }


        [Required(ErrorMessage = "City is required.")]
        public string City { get; set; }


        [Required(ErrorMessage = "County is required.")]
        public string County { get; set; }


        [Required(ErrorMessage = "Eircode is required.")]
        [Range(7, 7, ErrorMessage = "Invalid eircode has been entered.")]
        public string Eircode { get; set; }


        [Required(ErrorMessage = "A Phone Number is required.")]
        [DataType(DataType.PhoneNumber, ErrorMessage = "Invalid phone number has been entered.")]
        public string PhoneNumber { get; set; }


        [Required(ErrorMessage = "An Email is required.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Invalid Email has been entered.")]
        public string Email { get; set; }
    }
}
