services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=!SecurePassword123!
  asp_app:
    image: asp_app
    container_name: asp_app_container
    ports:
      - "5000:80"
    environment:
      - SQL_CONNECTION_STRING=Server=sql_server2022;Database=tempdb;User Id=SA;Password=!SecurePassword123!;MultipleActiveResultSets=true
      - IS_DOCKER_CONTAINER=YES